frontend/webapp/package-lock.json
frontend/webapp/package.json
frontend/webapp/postcss.config.js
frontend/webapp/src/app/components/AssistantInteraction.js
frontend/webapp/src/app/globals.css
frontend/webapp/tailwind.config.js

Added [tailwindcss](https://tailwindcss.com) to the dev dependecies, so devs (who want to) can use it to style their components.

Added tailwindcss to the dev dependecies

---

superheroes/superhero-03-02/.dockerignore
superheroes/superhero-03-02/Dockerfile
superheroes/superhero-03-02/app.js
superheroes/superhero-03-02/controllers/commandController.js
superheroes/superhero-03-02/package-lock.json
superheroes/superhero-03-02/package.json
superheroes/superhero-03-02/services/generativeAIService.js
superheroes/superhero-03-02/utils/plantumlUtils.js

Add superhero DiagramIt code to the repository

Add superhero DiagramIt to repo

---

superheroes/superhero-08-02/spark/api/services/github_graphql.py
superheroes/superhero-08-02/spark/api/services/miro.py

Created Miro Board Template API

Created Miro Board Template API

---

infrastructure/pipeline/cloudbuild.yaml

Passes GitHub App ID as an env var to Jarvis at deploy time

Added APP ID and GITHUB_ORG env vars to Jarvis at deploy

---

superheroes/superhero-08-02/spark/api/services/github_graphql.py
superheroes/superhero-08-02/spark/api/services/miro.py

Assistant/spark/Miro to GitHub API

Assistant/spark/Miro to GitHub API

---

superheroes/superhero-05-05/Dockerfile

Inject Sam's secret API key into Docker image in Dockerfile

Add secret to Dockerfile

---

avengers/frontend/webapp/src/app/assistants/story2test/components/Chat.jsx

Assistant's text appears as typing instead of popping up

Typing implementation

---

superheroes/superhero-06-02/Dockerfile
superheroes/superhero-06-02/manage.py
superheroes/superhero-06-02/requirements.txt

This PR includes the minimal setup for the superhero-06-02 backend Django service:
- Dockerfile for building and deploying the service.
- manage.py as the entry point.
- requirements.txt for specifying dependencies.
This setup is intended for initial pipeline validation. Future PRs will expand functionality.

Superhero 06 02 setup

---

x-men/ai4sd-helpers/package.json
x-men/ai4sd-helpers/src/extension.ts
x-men/ai4sd-helpers/src/superheroes/easycomment/.gitignore
x-men/ai4sd-helpers/src/superheroes/easycomment/.vscodeignore
x-men/ai4sd-helpers/src/superheroes/easycomment/CHANGELOG.md
x-men/ai4sd-helpers/src/superheroes/easycomment/README.md
x-men/ai4sd-helpers/src/superheroes/easycomment/eslint.config.mjs
x-men/ai4sd-helpers/src/superheroes/easycomment/package-lock.json
x-men/ai4sd-helpers/src/superheroes/easycomment/package.json
x-men/ai4sd-helpers/src/superheroes/easycomment/src/extension.ts
x-men/ai4sd-helpers/src/superheroes/easycomment/src/parsingModes/fileByfile.ts
x-men/ai4sd-helpers/src/superheroes/easycomment/src/test/extension.test.ts
x-men/ai4sd-helpers/src/superheroes/easycomment/tsconfig.json
x-men/ai4sd-helpers/src/superheroes/easycomment/vsc-extension-quickstart.md

Known bugs: 
Fix the local server to the cloud server
Changes:
Modified the shared extension.ts
There were no conflicts

Integrated EasyComment into AI4SDHELPER

---

x-men/ai4sd-helpers/src/superheroes/whattheduck/src/refactor/refactor.ts

The url on the what the duck extension was using `http` instead of `https`.
This PR fixes it.

fix: whattheduck x-men extension wrong backend url

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js
avengers/frontend/webapp/src/app/assistants/req2test/components/Chat.jsx
avengers/frontend/webapp/src/app/assistants/req2test/page.js
superheroes/superhero-01-03/api.py

Finished integration with AI4SD Vault (Firebase DB) for Req2Test.

Req2test Vault Integration

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js
avengers/frontend/webapp/src/app/assistants/req2test/components/Chat.jsx
superheroes/superhero-01-03/Dockerfile
superheroes/superhero-01-03/api.py
superheroes/superhero-01-03/gemini.py

Added the gemini API key in superhero-01-03's secret. Works locally and should work on the cloud.

superhero-01-03 Gemini Integration (w/ secret)

---

avengers/frontend/webapp/src/app/assistants/reqtostory/project/[projectId]/components/assistant.js
avengers/frontend/webapp/src/app/assistants/reqtostory/project/[projectId]/components/userStoryTable.js

Add frontend: 
- project/[projectId]/components/assistant.js: code to give feedback about a generated user story (either like or dislike) (#272)
- project/[projectId]/components/userStoryTable.js: code to create the like and dislike buttons

Assistant/superhero-04-02 - User Story Feedback

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js
avengers/frontend/webapp/src/app/assistants/req2test/page.js
superheroes/superhero-01-03/Dockerfile

Fixed API port (from 8000 to 8080) for superhero-01-03 (Req2Test)

Fixed API port for superhero-01-03 (Req2Test)

---

superheroes/superhero-07-04/Dockerfile
x-men/ai4sd-helpers/src/superheroes/easycomment/src/extension.ts

Changed from dockerfile to Dockerfile, git kept reseting to dockerfile
Also mini update to the EasyComment frontend

Changed dockerfile to Dockerfile

---

superheroes/superhero-07-04/src/server.ts
x-men/ai4sd-helpers/package.json

Added a default get for testing purposes

Assistant/easy comment/cloud integration request denied fix

---

avengers/frontend/webapp/src/app/assistants/toopai/components/Chat.jsx
avengers/frontend/webapp/src/app/assistants/toopai/components/index.css
superheroes/superhero-01-02/Dockerfile

i have added the secret to dockerfile, and minor frontend changes

dockerfile with secret and minor frontend changes

---

superheroes/superhero-03-03/Dockerfile
superheroes/superhero-03-03/src/app.js

Added secret injection at docker image build time.
Changed backend port from 3000 to 8080, dockerfile also reflects this.

Superhero 03 03 secrets

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js
avengers/frontend/webapp/src/app/assistants/req2test/components/Chat.jsx
avengers/frontend/webapp/src/app/assistants/req2test/components/Previewer.jsx
superheroes/superhero-01-03/api.py

The messages in the chat are now being updated as expected.

Fixing the firestore updates in superhero-01-03 (Req2Test)

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js

Changed  API URL to the cloud version of  superhero-01-03 (Req2Test)

Fixed API URL (again) for superhero-01-03 (Req2Test)

---

superheroes/superhero-05-03/.gitignore
superheroes/superhero-05-03/package-lock.json
superheroes/superhero-05-03/package.json

Added dotenv dependency so that the secret can be read in the server

Superhero 05 03 adding secrets

---

superheroes/superhero-05-03/Dockerfile

Changed previous command to new version. Hope it works

altered way secret is fetched in dockerfile

---

avengers/frontend/webapp/src/app/assistants/req2test/api/api.js
avengers/frontend/webapp/src/app/assistants/req2test/components/Chat.jsx
superheroes/superhero-01-03/api.py

Made some improvements to superhero-01-03 (Req2Test); general fixes and other quality of life improvements.l

Made some improvements to superhero-01-03 (Req2Test)

---

superheroes/superhero-05-03/Dockerfile
superheroes/superhero-05-03/package-lock.json
superheroes/superhero-05-03/package.json
superheroes/superhero-05-03/src/server.ts

reverted the secrets so that its hardcoded now

---

x-men/.vscode/launch.json
x-men/ai4sd-helpers/package.json
x-men/ai4sd-helpers/src/extension.ts
x-men/easycomment/.gitignore
x-men/easycomment/.vscodeignore
x-men/easycomment/CHANGELOG.md
x-men/easycomment/README.md
x-men/easycomment/eslint.config.mjs
x-men/easycomment/package-lock.json
x-men/easycomment/package.json
x-men/easycomment/src/extension.ts
x-men/easycomment/src/parsingModes/fileByfile.ts
x-men/easycomment/src/test/extension.test.ts
x-men/easycomment/tsconfig.json
x-men/easycomment/vsc-extension-quickstart.md

Integrated in a new way of frontend x-men

Assistant/easy comment/new integration

---

avengers/frontend/webapp/src/app/assistants/story2test/components/Chat.jsx

Frontend update

---

superheroes/superhero-07-01/functions.py

Update to key

---

x-men/ai4sd-chat-bots/src/superheroes/access-ai/.dockerignore
x-men/ai4sd-chat-bots/src/superheroes/access-ai/Dockerfile
x-men/ai4sd-chat-bots/src/superheroes/access-ai/docker-compose.yml

added a docker container for access-ai

Docker Setup
